### ISSUE TITLE
Marvin v5.1.0 has only 1 move but is thinking

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#11]
while testing engine-vs-engine in CuteChess, Marvin was thinking for 27 seconds in this position :

![Marvin_v5 1 0_NNUE_white_has_only_1_move_but_thinks_27sec](https://user-images.githubusercontent.com/1109281/126666088-63dae9a4-ccb2-418a-9828-21056f65828b.png)

it has only 1 move Kh2 .. what is it thinking ?

**Comment by bmdanielsson** [comment]
This is a bug. It should move instantly when there is only one legal move. This has been fixed now.

Thanks for reporting this issue!
