### ISSUE TITLE
Marvin v5.1.0 NNUE draws endgame while totally winning

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#13]
It's a pitty Marvin does not play the endgame well .. here's a position which is totally winning for White but Marvin lost the only pawn, which is always needed to win .. the game ended in a draw with K+N+N vs K : counting these material points, White has a big plus but mate is impossible ..

![dia_Marvin-vs-SF_Honey-WhiteMustWinButDraws](https://user-images.githubusercontent.com/1109281/126799152-3d1d007e-2abf-46ce-b72a-a507c5106b95.png)

the position has 8 pieces, so TBs will not help (we're in 2021) .. my SF 14 NNUE gives about +50 for White .. there are several ways to win, but Marvin should "know" the only pawn should never be lost !?
[PGN attached]

[Marvin-vs-SF_Honey-WhiteMustWinButDraws.zip](https://github.com/bmdanielsson/marvin-chess/files/6869517/Marvin-vs-SF_Honey-WhiteMustWinButDraws.zip)

**Comment by tissatussa** [comment]
another clear example : Marvin plays White and gives the pawn to get an exchange of pieces, but that pawn is needed for the win !

![Marvin-vs-ShashChess-WhiteMustWinButDraws](https://user-images.githubusercontent.com/1109281/126831974-504eafe3-51c3-4bc6-a963-917cdead788f.png)

**Comment by bmdanielsson** [comment]
With 5-men TB Marvin sees the problem with giving up the pawn in both positions. The reason is because it uses TB not only at the start of a search, but during the search as well. So in the second position it will score the position after the pawn and bishop has been captured as a draw.
