### ISSUE TITLE
FRC support?

### ISSUE THREAD

**Issue by CMCanavessi** [bmdanielsson/marvin-chess#15]
Hi! Do you have plans to implement FRC support in the future?

I saw commit 2b8384bf2d789ea14217234ee73be03a807f23c8 that has to do with FRC starting positions but I guess full support is not there yet?

**Comment by bmdanielsson** [comment]
FRC support is on the TODO list, but I don't know when I will get to it.

Today I only use the FRC starting positions when generating NNUE training data from self-play games in order to improve randomization and to also include some positions that are not as common (in regular chess).
