### ISSUE TITLE
Compile error with Android NDK

### ISSUE THREAD

**Issue by archimedeschess** [bmdanielsson/marvin-chess#16]
With Android NDK I get the following error message:
```
simd.c:245:40: fatal error: argument to '__builtin_neon_vshrn_n_v' must be a constant integer
int16x8_t lower = vcombine_s16(vshrn_n_s32(*(pi++), shift),
```

**Comment by bmdanielsson** [comment]
Thank you for reporting this. I don't have the Android NDK installed so I can't test but I think the changes below should do the trick. It would be great if you could test and confirm that it solves the issue.

diff --git a/src/simd.c b/src/simd.c
index 08b6948..f69afdd 100644
--- a/src/simd.c
+++ b/src/simd.c
@@ -166,7 +166,7 @@ void simd_fc_forward(uint8_t *input, int32_t *output, int ninputs,
 #endif
 }
 
-void simd_scale_and_clamp(int32_t *input, uint8_t *output, int shift,
+void simd_scale_and_clamp(int32_t *input, uint8_t *output, const int shift,
                           int nvalues)
 {
 #if defined(USE_AVX2)
diff --git a/src/simd.h b/src/simd.h
index 8dc477d..a5a27b3 100644
--- a/src/simd.h
+++ b/src/simd.h
@@ -51,7 +51,7 @@ void simd_fc_forward(uint8_t *input, int32_t *output, int ninputs,
  * @param shift Value to scale with.
  * @param nvalues The number of values.
  */
-void simd_scale_and_clamp(int32_t *input, uint8_t *output, int shift,
+void simd_scale_and_clamp(int32_t *input, uint8_t *output, const int shift,
                           int nvalues);

**Comment by archimedeschess** [comment]
Changing "int shift" to "const int shift" in simd_scale_and_clamp() function did not work either. The same error message appears. However, if you enter a fixed numerical value for the shift value in the respective function vshrn_n_s32, the compilation works. Can it be that this variable must already be known at compile time for vshrn_n_s32?

**Comment by bmdanielsson** [comment]
Ok, thanks for testing. Maybe you're right that it needs to know the value at compile time. I have to look into it some more. But at the moment 'shift' will always have the same value so an easy fix is to just replace it with the value '6'.

**Comment by archimedeschess** [comment]
Already tested with the value 6. Thanks also again for the confirmation and for the quick help.

**Comment by bmdanielsson** [comment]
Fix pushed.
