### ISSUE TITLE
default NNUE ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#17]
i just compiled your newest v6.2.0 source and all went well .. but i'm confused by the NNUE setting.

the command `uci` shows :

```
id name Marvin 6.2.0
id author Martin Danielsson
option name Hash type spin default 128 min 1 max 131072
option name OwnBook type check default true
option name Ponder type check default false
option name UCI_Chess960 type check default false
option name SyzygyPath type string default 
option name Threads type spin default 2 min 1 max 512
option name MultiPV type spin default 1 min 1 max 32
option name MoveOverhead type spin default 50 min 0 max 2000
option name LogLevel type spin default 3 min 0 max 2
option name UseNNUE type check default true
option name EvalFile type string default 
```

the last line shows the eval file will be 'default' .. i guess this is the new 'net-0d21cd7.nnue' as your release info states .. i got this file by the `make net` command .. i read _"A network file is included in the binaries package"_ but i didn't find it there .. also your ZIPped source does not contain any NNUE file ?!

my file size of the compiled binary is 20.2 MB (same as your pre-compiled assets) and the nnue file size is 20.0 Mb : so, i imagine the NNUE data could be embedded, leaving 200 Kb for the code ? While using (eg.) CuteChess for engine play, should i set the path/to/nnuefile in the options ? Or does Marvin auto-find its network by file name, being default ? You could create a message when the default NNUE file is missing in the folder ..

[ i'm on Xubuntu 22.04 ]

**Comment by bmdanielsson** [comment]
As you suspected the network file is embedded in the executable. I forgot to update the README file. The network files can be found at https://github.com/bmdanielsson/marvin-nets . This is where 'make net' downloads them from. 

In most cases you can just ignore the EvalFile option and Marvin will use the embedded network file. The option is there to make it easier to compare different networks with each other during development.

**Comment by tissatussa** [comment]
> I forgot to update the README file

OK .. good luck!
Marvin v6.2.0 is doing well, thanks.

**Comment by bmdanielsson** [comment]
README updated.
