### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [bmdanielsson/marvin-chess#18]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by bmdanielsson** [comment]
There is Neon support starting from version 6.2.0. Use the following command to build:
$ make arch=aarch64

This works on Raspberry Pi assuming you use a 64-bit OS. The same command will probably work for Android as well if you change the CC variable in the Makefile on line 135 to the name of you compiler. Regarding ARMv9.2, SVE2 and Dot product I would like to support that, but unfortunately I have no device that I can use to test this on.
