### ISSUE TITLE
Compile error on Raspberry Pi

### ISSUE THREAD

**Issue by djdekker** [bmdanielsson/marvin-chess#2]
Compiling Marvin 2.1.0 on Raspberry Pi fails with the following error:

```
import/fathom/tbprobe.c:33:23: fatal error: x86intrin.h: No such file or directory
 #include <x86intrin.h>
                       ^
compilation terminated.
Makefile:124: recipe for target 'import/fathom/tbprobe.o' failed
make: *** [import/fathom/tbprobe.o] Error 1
```

It is, of course, obvious that `x86intrin.h` (and also `popcntintrin.h`) is not supported on Raspberry Pi.

Is it possible to work around this problem, or is there perhaps a way to compile Marvin without table base support?

**Comment by bmdanielsson** [comment]
Thank you for reporting this.

I haven't tested but popcntintrin.h shouldn't be a problem if you build with "make popcnt=no". Regarding x86intrin.h it looks like it's not needed. I tried to just remove it and it seems to work.

I'll investigate some more and make a proper fix.

**Comment by bmdanielsson** [comment]
I have pushed a fix for the problem with x86intrin.h. With this fix I was able to do a cross-compile for Raspberry Pi with 'make popcnt=no'. If you have time it would be great if you could test if building works for you as well.

**Comment by djdekker** [comment]
Thank you Martin! Marvin is compiling fine now on Raspberry Pi, **if** additionally the flag -std=c11 is set. Otherwise gcc complains about tbprobe.c making 'for' loop declarations in the wrong manner. But with -std=c11 the result is a working binary! 👍

**Comment by bmdanielsson** [comment]
Great, thanks for testing!
