### ISSUE TITLE
pure NNUE evaluation ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#20]
on the Release page of v6.3.0 i see an 'Improvement' has changed : "Switch back to pure NNUE evaluation".
but an UCI checkbox exists called 'UseNNUE' ?
so, what does "pure NNUE evaluation" mean ?

besides that, my compiled v6.3.0 binary is under 2 Mb, just like your pre-compiled ones.
this differs from v6.2.0, which has a (embedded) default NNUE file of 20 Mb, but v6.3.0 has no default EvalFile (value is empty), i guess it uses the `res/eval.nnue` of 1.5 Mb ?

and i wonder : when UseNNUE is True, is HCE not used at all or is the eval a combination of NNUE and HCE ?

**Comment by bmdanielsson** [comment]
Hi,

Before Marvin would switch to HCE under some conditions even when using NNUE. In 6.3.0 it will always use NNUE if NNUE is enabled. The "Use NNUE" checkbox means always use HCE or always use NNUE.

Yes, the file res/eval.nnue is used. It is included in the pre-compiled binaries. The network in 6.3.0 is a lot smaller wh9ich is why the binary size is smaller.


/Martin
