### ISSUE TITLE
Marvin goes for a draw in a won game

### ISSUE THREAD

**Issue by NajdorfB** [bmdanielsson/marvin-chess#3]
In this game Marvin was up a Queen, Knight and Pawn. The own evaluation was +199.89, but the program decided to go for a three fold repetition. I don't have a log file, only the pgn. Not sure if this is helpful, but maybe the problem is reproducible.

[Marvin.zip](https://github.com/bmdanielsson/marvin-chess/files/3077664/Marvin.zip)

**Comment by bmdanielsson** [comment]
Thank you for reporting this! I haven't been able to reproduce it but the PGN gives some hints. Marvin selects Qa1 which leads to a draw, but the PV actually has the correct move (Qf2+). So it looks like there is a problem in how moves are reported.

Did you use UCI or Xboard/Winboard protocol? How many threads did you use?

**Comment by bmdanielsson** [comment]
I managed to reproduce the issue after some additional testing. Problem was caused by some struct fields that were not reset between searches.
