### ISSUE TITLE
Compiling gives v5.0.0-a5 !? and NNUE file missing ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#5]
hi, your GitHub page says it's version 4 but after compiling (on Linux) the command "uci" shows v5.0.0-a5 !?  And net-531cad4.nnue should be used as default, but where can i find this file ?  It's not in the ZIP package .. maybe it's included in the executable after compiling but it's not clear to me.  NOTE: in CuteChess i can setup any nnue file, so i did, and it seems to work ..

**Comment by bmdanielsson** [comment]
Hi,

Sorry for the confusion. 4.0.0 is the latest official release. However the source code reflects the development version used for TCEC Cup 7. If you want to build the 4.0.0 version there is a tag called v4.0.0 that points to the matching source code.

Once I make an official release of 5.0.0 the default net will be available on the releases page. But until then you can download the net from here: https://drive.google.com/file/d/1vZLth1ORhknsGfGOFFu3SYsZdOLmtoHg/view?usp=sharing .
