### ISSUE TITLE
using .ini file for default UCI settings ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#6]
about using an .ini file to get default UCI settings : when i give the command 'uci' Marvin 4.0.1 does not show the NNUE file path option, so when using CuteChess this option is not in the settings window .. however, CuteChess seems to read the .ini file - i checked it by changing hash and threads - but when adding 'EVAL_FILE=path-to-nnue-file' this option is not displayed in CuteChess .. is my format wrong ? I give the full path from root .. or is an NNUE included in the binairy ? Also by compiling ? I may give CuteChess some uci parameter but i don't know how .. or you could create all ini-settings as uci options and remove the .ini file ?

**Comment by bmdanielsson** [comment]
Sounds strange that the NNUE path option doesn't show up. You should get an option called EvalFile where you can set the NNUE path. Which commit did you build from?

The .ini is mainly intended to be used with the Xboard protocol (CECP) since with that protocol it's the only way to specify some settings. For UCI it's completely optional and if you're using a GUI like CuteChess I would recommend not using it.

**Comment by tissatussa** [comment]
I downloaded the Master ZIP again and compiled it : now all seems OK !  See screenshot of the CuteChess Config.  I must have had an older version - sorry.  Thanks for the info about the .ini file usage.

![CuteChess_Marvin_settings](https://user-images.githubusercontent.com/1109281/99878222-2b20e700-2c04-11eb-95a1-961cce97488a.png)

**Comment by bmdanielsson** [comment]
Glad that it works now. A slight note on versions. What you're testing is not the 4.0.1 version, instead you're testing the latest development version. This is what will become version 5.0.0 once I release it. If you want to test 4.0.1 you can either download the source code zip from the releases page, or switch to the rel/4.0.x branch on the main page and then download the zip with "Code" button as usual. However note that the 4.0.1 version doesn't have NNUE support so If that's what you're interested in testing then you have to use the development version.
