### ISSUE TITLE
NNUE file usage

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#7]
I use CuteChess to run Marvin v4.0.1 NNUE .. the 'uci' command tells me the EVAL_FILE default value is 'net-531cad4.nnue' but this is not a seperate file and not included in the ZIP .. is this NN compiled into the binairy ?  Do i then need to give a path-to-nnue-file in the CuteChess Config settings ?

Do NNUE files exist which are suited for your engine or can i use any NNUE file i find on the internet ? (and give its proper path-to-file as EVAL_FILE value and set useNNUE True) .. I found several NNUE files, they often are about 20 Mb.  Where to get them ?

Can i rename any NNUE file, to be equal to the default name ?  Or must any NNUE file be named as is ?

**Comment by bmdanielsson** [comment]
The 'net-531cad4.nnue' can be downloaded from here, https://drive.google.com/file/d/1vZLth1ORhknsGfGOFFu3SYsZdOLmtoHg/view?usp=sharing . Just put it in the same directory as the engine binary and the default settings will work. At the moment Marvin uses the same format for NNUE files as Stockfish, so any Stockfish net should work as well. However this will most likely change in the future. To use another net put it in the same directory as the engine binary and just change the name in UCI settings in CuteChess.
