### ISSUE TITLE
Marvin v5.0.0 no NNUE active ?

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#9]
Using CuteChess to let Marvin v5.0.0 play against another engine, it seems the NNUE function is not active .. however, v4.0.1 does function with same settings in CuteChess. This is my CuteChess config setting of Marvin v5.0.0 :

![Marvin_v5 0 0_CuteChess_config](https://user-images.githubusercontent.com/1109281/107102310-6487ec80-681a-11eb-855a-32cb26aa8c48.png)

but i get this error message when a game starts :

![Marvin_v5 0 0_noinit](https://user-images.githubusercontent.com/1109281/107102328-6baefa80-681a-11eb-9a3c-b30fe99bbead.png)

i tried to use the NN file 'net-3f7389e.nnue' (10 Mb, in marvin_5.0.0_binaries.zip) and also 'net-531cad4.nnue' (20 Mb, the one that came with v4.0.1) but both give the same error .. however, v4.0.1 does function with both NN files.

in the directory where the Marvin v5.0.0 binary is, i put NO .ini file (although the Readme.md tells about it) but CuteChess displays all its options in the config popup window, so i guess Marvin v5.0.0 has defaults because v4.0.1 DOES function properly without an .ini file .. 

after v5.0.0 crashed, the log file shows these 3 lines :

==> setoption name MultiPV value 1
==> setoption name OwnBook value false
==> setoption name SyzygyPath

so, the NNUE option is not set, although the CuteChess config has it ..

what's wrong ?
is it a bug ?
am i missing something ?
i tried a compiled binary and also a pre-compiled x86_64_modern from the ZIP.

**Comment by bmdanielsson** [comment]
Thank you for reporting this problem.

You're configuring everything correctly, this is a bug in Marvin. The command 'setoption name SyzygyPath' is incomplete which causes Marvin to crash. I suspect that the reason CuteChess sends this incomplete command is because the SyzygyPath option is empty in the CuteChess config. So an easy workaround until I fix the bug in Marvin would be to enter a dummy value for the SyzygyPath option in the CuteChess configuration.

**Comment by tissatussa** [comment]
Indeed, this is the solution !

I put "." as dummy path value and now Marvin v5.0.0 is working.  NOTE: in CuteChess the default config of Marvin v4.0.1 has SyzygyPath "\<empty\>".

**Comment by bmdanielsson** [comment]
Fixed. Improved parsing of UCI options.
